### ISSUE TITLE
simulink support

### ISSUE THREAD

**Issue by feiyuxiaoThu** [qpSWIFT/qpSWIFT#1]
Thanks for your code. I used the S-function method to include the c codes however failed and I thought the main problem might be the lib file. I noticed you have added a /simulink interface so I am looking forward to your solution. Thanks again!

**Comment by abhishek-pandala** [comment]
Hi feiyuxiaoThu. We have updated the simulink code. You can find the demo files in [demoqp.slx](https://github.com/qpSWIFT/qpSWIFT/blob/main/simulink/demoqp.slx) [demoqp_e.slx](https://github.com/qpSWIFT/qpSWIFT/blob/main/simulink/demoqp_e.slx). The pdf documentation and wiki documentation are also updated. Have a look at it and let us know your feedback
