### ISSUE TITLE
Solving Linear Programs using qpSWIFT

### ISSUE THREAD

**Issue by trivediana** [qpSWIFT/qpSWIFT#11]
Hello,
Thanks for making your solver public. It is of great use in my research. I had a question regarding using qpSWIFT as a linear programming solver. For my application, I need to solve both an LP and a QP at real time rates. So I was thinking of using qpSWIFT as a common solver with the LP being solved by setting the P matrix to zero. Do you expect any efficiency shortcomings as a result? Thanks again!

**Comment by abhishek-pandala** [comment]
Hi,
    Thank you for your interest in the solver. Solving LP by setting the P matrix to zero is not a good idea as this might lead to numerical issues in the LDL factorization. Furthermore, the solution of LP and QP can be vastly different even if the P matrix is very close to zero matrix. Hope this helps.
