### ISSUE TITLE
Warm Start Support

### ISSUE THREAD

**Issue by feiyuxiaoThu** [qpSWIFT/qpSWIFT#5]
Thanks for your recent updates.
I have used your QP solver in my autonomous vehicle research and it performs well.
Is it possible to add warm start support because in many cases several feasible solution can be easily get, and this approach might possibly accelerate the solving process?

**Comment by abhishek-pandala** [comment]
Hi feiyuxiaoThu, qpSWIFT relies on interior point methods to compute solutions for quadratic programs. It is known in the literature that interior point methods are not very amenable to warm-starting. As such, we do not intend to support warm - starting as of now. This can be part of future work.
